name :  Complex Math Ops Job with Matrix Stratagy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: environment value
      space:
        required: true
        type: string
        description: space value
      method_name:
        required: true
        type: string
        description: method name value
      skiptest:
        required: true
        type: boolean
        description: skipping test cases
      arg_a:
        required: true
        type: string
        description: enter first argument
      arg_b:
        required: true
        type: string
        description: enter second argument


jobs:
  build_job:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run unit tests
        if: ${{ !inputs.skiptest }}
        run: pytest generic --cov
  run_job:
    needs: build_job
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arg_x: [10 , 20 , 30]
        arg_y: [40 , 50 , 60]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run python script
        run: python generic/functs/run_code.py ${{ matrix.arg_x }} ${{ matrix.arg_y }}
