name :  Complex Math Ops Job with github variables and secrets

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: environment value
      space:
        required: true
        type: string
        description: space value
    secrets:
      SEC_ONE:
        required: true


jobs:
  build_job:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run unit tests
        if: ${{ !inputs.skiptest }}
        run: pytest generic --cov
  run_job:
    needs: build_job
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      SEC_ONE: ${{ secrets.SEC_ONE }}
      VAR_ONE: ${{ vars.VAR_ONE }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run python script
        run: python generic/functs/run_code_two.py
