name :  Complex Math Ops Job With If Condition

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: environment value
      space:
        required: true
        type: string
        description: space value
      method_name:
        required: true
        type: string
        description: method name value
      skiptest:
        required: false
        type: boolean
        description: skipping test cases
      deployjob:
        required: true
        type: boolean
        description: job sjould be deployed or not


jobs:
  build_job:
    if: ${{ inputs.deployjob == true }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run unit tests
        if: ${{ inputs.skiptest == false }}
        run: pytest generic --cov
  run_job:
    needs: build_job
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run python script
        run: python generic/functs/run_code.py

